/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  startedBar: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      items: ["getting-started"]
    }
  ],
  tokenBar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "foundations/introduction"
        }
      ]
    },
    {
      type: "category",
      label: "Foundations",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "foundations/our-tokens"
        }
      ]
    }
  ],
  designBar: [
    {
      type: "category",
      label: "Components",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "design/uncategorized"
        }
      ]
    },
    {
      type: "category",
      label: "Inputs",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "design/inputs"
        }
      ]
    }
  ],
  devBar: [
    {
      type: "category",
      label: "Components",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "dev/uncategorized"
        }
      ]
    },
    {
      type: "category",
      label: "Inputs",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "dev/inputs"
        }
      ]
    }
  ],

  resourceBar: [
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "resources"
        }
      ]
    }
  ],

  releaseNotesBar: [
    {
      type: "category",
      label: "Release Notes",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "release-notes"
        }
      ]
    }
  ]
};
