/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  startedBar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/getting-started'],
    },
  ],
  tokenBar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible:false,
      items: [{
        type:'autogenerated',
        dirName:'tokens/introduction'
      }],
    },
    {
      type: 'category',
      label: 'Tokens',
      collapsible:false,
      items: [{
        type:'autogenerated',
        dirName:'tokens/our-tokens'
      }],
    },

  ],
};
