import Head from "next/head";
import React, { useState } from "react";
import { TinaProvider, TinaCMS, useCMS, useForm, usePlugin } from "tinacms";
import styles from "../styles/Home.module.css";

function Home() {
  const [CMSEnabled, setCMSEnabled] = useState(false);
  const cms = new TinaCMS({
    sidebar: true,
    enabled: CMSEnabled,
  });

  function EditButton() {
    const cms = useCMS();
    return (
      <button onClick={() => cms.toggle()}>
        {cms.enabled ? "Exit Edit Mode" : "Edit This Site"}
      </button>
    );
  }
  const pageData={
    title:"Hey there"
  }
  const formConfig = {
    id: "main-page",
    label: "Main Page",
    fields: [
      {
        name: "title",
        label: "Title",
        component: "text",
      },
    ],
    initialValue:pageData,
    onSubmit: async () => {
      window.alert("Saved!");
    },
  };
  const [editableData, form] = useForm(formConfig);
  usePlugin(form);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>{editableData.title}</h1>
          <EditButton/>
        </main>
    </div>
  );
}
export default Home;
